[project]
name = "project-two-acr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.53.0",
    "pyttsx3>=2.98",
]
